algoritmo "conteATE10"
// Função :
// Autor :
// Data : 15/06/2022
// Seção de Declarações
var
valor, contador, salto:inteiro
inicio
contador <- 0
escreval("quer contar até quanto ? ")
leia(valor)
escreva("qual sera o valor do salto?")
leia(salto)
enquanto (contador <=valor) faca
   escreval(contador)
   contador <- contador + salto
   fimEnquanto
   escreval ("terminei de contar")
   
   
   fimalgoritmo
